### ISSUE TITLE
kernel名称带来的脚本问题

### ISSUE THREAD

**Issue by Jejz168** [Tao173/Auto-Update-Router#1]
echo '暂无空解决kernel名称带来的脚本问题，放弃修改，可自行摸索'
sudo apt install rename
# rename "s/flippy//" ./backup/breakings_kernel/*/*
# rename "s/flippy-//" ./backup/ophub_kernel/*/*/*/*

这个只是把文件名字改了，压缩文件里面还是原来的名字。所有编译的时候就出错了

**Comment by Tao173** [comment]
不是，我准备的有两个选项，使用rename改拉取的内核名称，我试了一下，但是跟着得改打包脚本，然后我懒得搞了，反正就是改个终端显示的名称和web概览的内核名称而已，然后我在打包脚本里面重新赋值了新的内核名称，这样ttyd的显示搞定，然后web概览的内核名称我通过修改主题实现的，目前一切正常。（我是菜鸡，瞎折腾的）

**Comment by Tao173** [comment]
![image](https://user-images.githubusercontent.com/64321391/170457135-9f2e1b60-c81a-40a4-8c4a-59a0fe69f3f0.png)

![image](https://user-images.githubusercontent.com/64321391/170457348-ac207b83-6359-49e5-b94c-ddaf91b1134f.png)

**Comment by Jejz168** [comment]
我也是菜鸡，不过可以自己编译内核，然后在上传到文件夹去

**Comment by Jejz168** [comment]
我看见了。你的命令./public_funcs改了这里

**Comment by Tao173** [comment]
内核编译也考虑过，主要是没时间维护。。。还是直接拉大佬们编译好的比较快捷。其实改名也是多余，尊重大佬们的工作应该保留名称的，自己瞎折腾搞得这些。而且我这个最近有点问题，还在调试，想迁回官方版本或者是国人维护的官方版本。

**Comment by Jejz168** [comment]
不是大雕的吗？内核编译也全自动的。我现在只要5.4版本的

**Comment by Tao173** [comment]
昨天之前使用的是大雕的，但是有点问题，U盘启动的话web、ttyd、winscp都不需要密码，因为编译脚本里面去了密码，但是一旦安装到emmc，后面两个会出现不知名密码，尝试过passwd和password都不行，然后我试着拿Lienol的源码编译了一个，完全正常不需要密码，他的是op官方版本维护的吧，21.02，他的用起来也可以，插件少了四个，现在正在编译天灵维护的21.02版本，看看吧，谁好用谁的。

**Comment by Jejz168** [comment]
我用的大雕的。还可以。没去掉密码。我x86也是用的大雕的

**Comment by Tao173** [comment]
> 我用的大雕的。还可以。没去掉密码。我x86也是用的大雕的

大雕确实还可以，折腾嘛，可能明天我也回去了。

**Comment by Tao173** [comment]
> 实时监控害人。用三方汉化打不开。还是用回原版自带的。又要编译了

嗯，那个插件我在telegram群说了一声，没人理。。。昨天就出问题了，一直编译不过，我已经先删了，弄好迁移之后在补上。

**Comment by Jejz168** [comment]
是原地址的依赖删了。只有app。没用。我直接不用了。回原英文的算了

**Comment by Tao173** [comment]
我准备自己编内核了，这样不用自己改脚本来修改内核名称了。

**Comment by Jejz168** [comment]
我用armbian了。感觉挺稳的。今天玩了一天

**Comment by Jejz168** [comment]
https://t.me/JejzBf

**Comment by Jejz168** [comment]
https://t.me/JejzBf      加我TG
